// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lobby.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Schema.Protobuf.Message.Lobby {

  /// <summary>Holder for reflection information generated from Lobby.proto</summary>
  public static partial class LobbyReflection {

    #region Descriptor
    /// <summary>File descriptor for Lobby.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LobbyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtMb2JieS5wcm90bxIdU2NoZW1hLlByb3RvYnVmLk1lc3NhZ2UuTG9iYnka",
            "C0VudW1zLnByb3RvIlcKBkxvZ291dBJACgtSZXBvbnNlQ29kZRhlIAEoDjIr",
            "LlNjaGVtYS5Qcm90b2J1Zi5NZXNzYWdlLkVudW1zLlJlc3BvbnNlQ29kZRIL",
            "CgNJZHgYZiABKANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Schema.Protobuf.Message.Enums.EnumsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Lobby.Logout), global::Schema.Protobuf.Message.Lobby.Logout.Parser, new[]{ "ReponseCode", "Idx" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Logout : pb::IMessage<Logout> {
    private static readonly pb::MessageParser<Logout> _parser = new pb::MessageParser<Logout>(() => new Logout());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Logout> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Lobby.LobbyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Logout() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Logout(Logout other) : this() {
      reponseCode_ = other.reponseCode_;
      idx_ = other.idx_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Logout Clone() {
      return new Logout(this);
    }

    /// <summary>Field number for the "ReponseCode" field.</summary>
    public const int ReponseCodeFieldNumber = 101;
    private global::Schema.Protobuf.Message.Enums.ResponseCode reponseCode_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Enums.ResponseCode ReponseCode {
      get { return reponseCode_; }
      set {
        reponseCode_ = value;
      }
    }

    /// <summary>Field number for the "Idx" field.</summary>
    public const int IdxFieldNumber = 102;
    private long idx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Idx {
      get { return idx_; }
      set {
        idx_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Logout);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Logout other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ReponseCode != other.ReponseCode) return false;
      if (Idx != other.Idx) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ReponseCode != 0) hash ^= ReponseCode.GetHashCode();
      if (Idx != 0L) hash ^= Idx.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ReponseCode != 0) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) ReponseCode);
      }
      if (Idx != 0L) {
        output.WriteRawTag(176, 6);
        output.WriteInt64(Idx);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ReponseCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ReponseCode);
      }
      if (Idx != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Idx);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Logout other) {
      if (other == null) {
        return;
      }
      if (other.ReponseCode != 0) {
        ReponseCode = other.ReponseCode;
      }
      if (other.Idx != 0L) {
        Idx = other.Idx;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 808: {
            reponseCode_ = (global::Schema.Protobuf.Message.Enums.ResponseCode) input.ReadEnum();
            break;
          }
          case 816: {
            Idx = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
