// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Game.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Schema.Protobuf.Message.Game {

  /// <summary>Holder for reflection information generated from Game.proto</summary>
  public static partial class GameReflection {

    #region Descriptor
    /// <summary>File descriptor for Game.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpHYW1lLnByb3RvEhxTY2hlbWEuUHJvdG9idWYuTWVzc2FnZS5HYW1lGgtF",
            "bnVtcy5wcm90bxoMQ29tbW9uLnByb3RvIl8KDUJlZ2luTWF0Y2hpbmcSCwoD",
            "TU1SGAEgASgFEkEKDFJlc3BvbnNlQ29kZRhlIAEoDjIrLlNjaGVtYS5Qcm90",
            "b2J1Zi5NZXNzYWdlLkVudW1zLlJlc3BvbnNlQ29kZSJTCg5DYW5jZWxNYXRj",
            "aGluZxJBCgxSZXNwb25zZUNvZGUYZSABKA4yKy5TY2hlbWEuUHJvdG9idWYu",
            "TWVzc2FnZS5FbnVtcy5SZXNwb25zZUNvZGUilAEKC0VuZE1hdGNoaW5nEkEK",
            "DFJlc3BvbnNlQ29kZRhlIAEoDjIrLlNjaGVtYS5Qcm90b2J1Zi5NZXNzYWdl",
            "LkVudW1zLlJlc3BvbnNlQ29kZRJCCgxNYXRjaGluZ0luZm8YZiABKAsyLC5T",
            "Y2hlbWEuUHJvdG9idWYuTWVzc2FnZS5Db21tb24uTWF0Y2hpbmdJbmZvIsAB",
            "CglFbnRlclJvb20SQQoMUmVzcG9uc2VDb2RlGGUgASgOMisuU2NoZW1hLlBy",
            "b3RvYnVmLk1lc3NhZ2UuRW51bXMuUmVzcG9uc2VDb2RlEhQKDEdhbWVTZXJ2",
            "ZXJJZBhmIAEoAxIOCgZSb29tSWQYZyABKAMSCwoDSWR4GGggASgDEj0KCkNo",
            "YXJhY3RlcnMYaSADKAsyKS5TY2hlbWEuUHJvdG9idWYuTWVzc2FnZS5Db21t",
            "b24uQ2hhcmFjdGVyImsKCUxlYXZlUm9vbRJBCgxSZXNwb25zZUNvZGUYZSAB",
            "KA4yKy5TY2hlbWEuUHJvdG9idWYuTWVzc2FnZS5FbnVtcy5SZXNwb25zZUNv",
            "ZGUSDgoGUm9vbUlkGGYgASgDEgsKA0lkeBhnIAEoAyJeCg5FbnRlckNoYXJh",
            "Y3RlchIOCgZSb29tSWQYZSABKAMSPAoJQ2hhcmFjdGVyGGYgASgLMikuU2No",
            "ZW1hLlByb3RvYnVmLk1lc3NhZ2UuQ29tbW9uLkNoYXJhY3RlciJeCg5MZWF2",
            "ZUNoYXJhY3RlchIOCgZSb29tSWQYZSABKAMSPAoJQ2hhcmFjdGVyGGYgASgL",
            "MikuU2NoZW1hLlByb3RvYnVmLk1lc3NhZ2UuQ29tbW9uLkNoYXJhY3RlciI2",
            "CgZEYW1hZ2USCwoDSWR4GAEgASgDEhAKCE90aGVySWR4GAIgASgDEg0KBVBv",
            "d2VyGAMgASgDIhIKA0RpZRILCgNJZHgYZSABKAMiiwEKDE15R2FtZVJlc3Vs",
            "dBJBCgxSZXNwb25zZUNvZGUYZSABKA4yKy5TY2hlbWEuUHJvdG9idWYuTWVz",
            "c2FnZS5FbnVtcy5SZXNwb25zZUNvZGUSOAoERGF0YRhmIAEoCzIqLlNjaGVt",
            "YS5Qcm90b2J1Zi5NZXNzYWdlLkNvbW1vbi5HYW1lUmVzdWx0IooBCgpGaW5p",
            "c2hHYW1lEkEKDFJlc3BvbnNlQ29kZRhlIAEoDjIrLlNjaGVtYS5Qcm90b2J1",
            "Zi5NZXNzYWdlLkVudW1zLlJlc3BvbnNlQ29kZRI5CgVEYXRhcxhmIAMoCzIq",
            "LlNjaGVtYS5Qcm90b2J1Zi5NZXNzYWdlLkNvbW1vbi5HYW1lUmVzdWx0Im8K",
            "BENoYXQSCwoDSWR4GAEgASgDEgoKAklkGAIgASgJEgsKA21zZxgDIAEoCRJB",
            "CgxSZXNwb25zZUNvZGUYZSABKA4yKy5TY2hlbWEuUHJvdG9idWYuTWVzc2Fn",
            "ZS5FbnVtcy5SZXNwb25zZUNvZGUiTAoIU3luY1RpbWUSFQoNU2VuZExvY2Fs",
            "VGltZRgBIAEoAxIVCg1SZWN2TG9jYWxUaW1lGAIgASgDEhIKClJlbW90ZVRp",
            "bWUYZSABKAMiqAEKBE1vdmUSCwoDSWR4GAEgASgDEjkKCFBvc2l0aW9uGAIg",
            "ASgLMicuU2NoZW1hLlByb3RvYnVmLk1lc3NhZ2UuQ29tbW9uLlZlY3RvcjMS",
            "OgoJRGlyZWN0aW9uGAMgASgLMicuU2NoZW1hLlByb3RvYnVmLk1lc3NhZ2Uu",
            "Q29tbW9uLlZlY3RvcjMSDQoFU3BlZWQYBCABKAISDQoFVGlja3MYBSABKAMi",
            "HwoDUlRUEgsKA0lkeBgBIAEoAxILCgNTZXEYAiABKAMingEKBVdvcmxkEj0K",
            "CkNoYXJhY3RlcnMYZSADKAsyKS5TY2hlbWEuUHJvdG9idWYuTWVzc2FnZS5D",
            "b21tb24uQ2hhcmFjdGVyEjUKA01hcBhmIAEoCzIoLlNjaGVtYS5Qcm90b2J1",
            "Zi5NZXNzYWdlLkNvbW1vbi5QbGFuZU1hcBILCgNTZXEYZyABKAMSEgoKRGVs",
            "dGFUaWNrcxhoIAEoA2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Schema.Protobuf.Message.Enums.EnumsReflection.Descriptor, global::Schema.Protobuf.Message.Common.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.BeginMatching), global::Schema.Protobuf.Message.Game.BeginMatching.Parser, new[]{ "MMR", "ResponseCode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.CancelMatching), global::Schema.Protobuf.Message.Game.CancelMatching.Parser, new[]{ "ResponseCode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.EndMatching), global::Schema.Protobuf.Message.Game.EndMatching.Parser, new[]{ "ResponseCode", "MatchingInfo" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.EnterRoom), global::Schema.Protobuf.Message.Game.EnterRoom.Parser, new[]{ "ResponseCode", "GameServerId", "RoomId", "Idx", "Characters" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.LeaveRoom), global::Schema.Protobuf.Message.Game.LeaveRoom.Parser, new[]{ "ResponseCode", "RoomId", "Idx" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.EnterCharacter), global::Schema.Protobuf.Message.Game.EnterCharacter.Parser, new[]{ "RoomId", "Character" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.LeaveCharacter), global::Schema.Protobuf.Message.Game.LeaveCharacter.Parser, new[]{ "RoomId", "Character" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.Damage), global::Schema.Protobuf.Message.Game.Damage.Parser, new[]{ "Idx", "OtherIdx", "Power" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.Die), global::Schema.Protobuf.Message.Game.Die.Parser, new[]{ "Idx" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.MyGameResult), global::Schema.Protobuf.Message.Game.MyGameResult.Parser, new[]{ "ResponseCode", "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.FinishGame), global::Schema.Protobuf.Message.Game.FinishGame.Parser, new[]{ "ResponseCode", "Datas" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.Chat), global::Schema.Protobuf.Message.Game.Chat.Parser, new[]{ "Idx", "Id", "Msg", "ResponseCode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.SyncTime), global::Schema.Protobuf.Message.Game.SyncTime.Parser, new[]{ "SendLocalTime", "RecvLocalTime", "RemoteTime" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.Move), global::Schema.Protobuf.Message.Game.Move.Parser, new[]{ "Idx", "Position", "Direction", "Speed", "Ticks" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.RTT), global::Schema.Protobuf.Message.Game.RTT.Parser, new[]{ "Idx", "Seq" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.World), global::Schema.Protobuf.Message.Game.World.Parser, new[]{ "Characters", "Map", "Seq", "DeltaTicks" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class BeginMatching : pb::IMessage<BeginMatching> {
    private static readonly pb::MessageParser<BeginMatching> _parser = new pb::MessageParser<BeginMatching>(() => new BeginMatching());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BeginMatching> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BeginMatching() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BeginMatching(BeginMatching other) : this() {
      mMR_ = other.mMR_;
      responseCode_ = other.responseCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BeginMatching Clone() {
      return new BeginMatching(this);
    }

    /// <summary>Field number for the "MMR" field.</summary>
    public const int MMRFieldNumber = 1;
    private int mMR_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MMR {
      get { return mMR_; }
      set {
        mMR_ = value;
      }
    }

    /// <summary>Field number for the "ResponseCode" field.</summary>
    public const int ResponseCodeFieldNumber = 101;
    private global::Schema.Protobuf.Message.Enums.ResponseCode responseCode_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Enums.ResponseCode ResponseCode {
      get { return responseCode_; }
      set {
        responseCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BeginMatching);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BeginMatching other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MMR != other.MMR) return false;
      if (ResponseCode != other.ResponseCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MMR != 0) hash ^= MMR.GetHashCode();
      if (ResponseCode != 0) hash ^= ResponseCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MMR != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MMR);
      }
      if (ResponseCode != 0) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) ResponseCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MMR != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MMR);
      }
      if (ResponseCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BeginMatching other) {
      if (other == null) {
        return;
      }
      if (other.MMR != 0) {
        MMR = other.MMR;
      }
      if (other.ResponseCode != 0) {
        ResponseCode = other.ResponseCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            MMR = input.ReadInt32();
            break;
          }
          case 808: {
            responseCode_ = (global::Schema.Protobuf.Message.Enums.ResponseCode) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CancelMatching : pb::IMessage<CancelMatching> {
    private static readonly pb::MessageParser<CancelMatching> _parser = new pb::MessageParser<CancelMatching>(() => new CancelMatching());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CancelMatching> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CancelMatching() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CancelMatching(CancelMatching other) : this() {
      responseCode_ = other.responseCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CancelMatching Clone() {
      return new CancelMatching(this);
    }

    /// <summary>Field number for the "ResponseCode" field.</summary>
    public const int ResponseCodeFieldNumber = 101;
    private global::Schema.Protobuf.Message.Enums.ResponseCode responseCode_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Enums.ResponseCode ResponseCode {
      get { return responseCode_; }
      set {
        responseCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CancelMatching);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CancelMatching other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResponseCode != other.ResponseCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResponseCode != 0) hash ^= ResponseCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ResponseCode != 0) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) ResponseCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResponseCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CancelMatching other) {
      if (other == null) {
        return;
      }
      if (other.ResponseCode != 0) {
        ResponseCode = other.ResponseCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 808: {
            responseCode_ = (global::Schema.Protobuf.Message.Enums.ResponseCode) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class EndMatching : pb::IMessage<EndMatching> {
    private static readonly pb::MessageParser<EndMatching> _parser = new pb::MessageParser<EndMatching>(() => new EndMatching());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EndMatching> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EndMatching() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EndMatching(EndMatching other) : this() {
      responseCode_ = other.responseCode_;
      MatchingInfo = other.matchingInfo_ != null ? other.MatchingInfo.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EndMatching Clone() {
      return new EndMatching(this);
    }

    /// <summary>Field number for the "ResponseCode" field.</summary>
    public const int ResponseCodeFieldNumber = 101;
    private global::Schema.Protobuf.Message.Enums.ResponseCode responseCode_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Enums.ResponseCode ResponseCode {
      get { return responseCode_; }
      set {
        responseCode_ = value;
      }
    }

    /// <summary>Field number for the "MatchingInfo" field.</summary>
    public const int MatchingInfoFieldNumber = 102;
    private global::Schema.Protobuf.Message.Common.MatchingInfo matchingInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Common.MatchingInfo MatchingInfo {
      get { return matchingInfo_; }
      set {
        matchingInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EndMatching);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EndMatching other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResponseCode != other.ResponseCode) return false;
      if (!object.Equals(MatchingInfo, other.MatchingInfo)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResponseCode != 0) hash ^= ResponseCode.GetHashCode();
      if (matchingInfo_ != null) hash ^= MatchingInfo.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ResponseCode != 0) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) ResponseCode);
      }
      if (matchingInfo_ != null) {
        output.WriteRawTag(178, 6);
        output.WriteMessage(MatchingInfo);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResponseCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseCode);
      }
      if (matchingInfo_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(MatchingInfo);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EndMatching other) {
      if (other == null) {
        return;
      }
      if (other.ResponseCode != 0) {
        ResponseCode = other.ResponseCode;
      }
      if (other.matchingInfo_ != null) {
        if (matchingInfo_ == null) {
          matchingInfo_ = new global::Schema.Protobuf.Message.Common.MatchingInfo();
        }
        MatchingInfo.MergeFrom(other.MatchingInfo);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 808: {
            responseCode_ = (global::Schema.Protobuf.Message.Enums.ResponseCode) input.ReadEnum();
            break;
          }
          case 818: {
            if (matchingInfo_ == null) {
              matchingInfo_ = new global::Schema.Protobuf.Message.Common.MatchingInfo();
            }
            input.ReadMessage(matchingInfo_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class EnterRoom : pb::IMessage<EnterRoom> {
    private static readonly pb::MessageParser<EnterRoom> _parser = new pb::MessageParser<EnterRoom>(() => new EnterRoom());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EnterRoom> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterRoom() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterRoom(EnterRoom other) : this() {
      responseCode_ = other.responseCode_;
      gameServerId_ = other.gameServerId_;
      roomId_ = other.roomId_;
      idx_ = other.idx_;
      characters_ = other.characters_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterRoom Clone() {
      return new EnterRoom(this);
    }

    /// <summary>Field number for the "ResponseCode" field.</summary>
    public const int ResponseCodeFieldNumber = 101;
    private global::Schema.Protobuf.Message.Enums.ResponseCode responseCode_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Enums.ResponseCode ResponseCode {
      get { return responseCode_; }
      set {
        responseCode_ = value;
      }
    }

    /// <summary>Field number for the "GameServerId" field.</summary>
    public const int GameServerIdFieldNumber = 102;
    private long gameServerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long GameServerId {
      get { return gameServerId_; }
      set {
        gameServerId_ = value;
      }
    }

    /// <summary>Field number for the "RoomId" field.</summary>
    public const int RoomIdFieldNumber = 103;
    private long roomId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long RoomId {
      get { return roomId_; }
      set {
        roomId_ = value;
      }
    }

    /// <summary>Field number for the "Idx" field.</summary>
    public const int IdxFieldNumber = 104;
    private long idx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Idx {
      get { return idx_; }
      set {
        idx_ = value;
      }
    }

    /// <summary>Field number for the "Characters" field.</summary>
    public const int CharactersFieldNumber = 105;
    private static readonly pb::FieldCodec<global::Schema.Protobuf.Message.Common.Character> _repeated_characters_codec
        = pb::FieldCodec.ForMessage(842, global::Schema.Protobuf.Message.Common.Character.Parser);
    private readonly pbc::RepeatedField<global::Schema.Protobuf.Message.Common.Character> characters_ = new pbc::RepeatedField<global::Schema.Protobuf.Message.Common.Character>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Schema.Protobuf.Message.Common.Character> Characters {
      get { return characters_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EnterRoom);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EnterRoom other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResponseCode != other.ResponseCode) return false;
      if (GameServerId != other.GameServerId) return false;
      if (RoomId != other.RoomId) return false;
      if (Idx != other.Idx) return false;
      if(!characters_.Equals(other.characters_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResponseCode != 0) hash ^= ResponseCode.GetHashCode();
      if (GameServerId != 0L) hash ^= GameServerId.GetHashCode();
      if (RoomId != 0L) hash ^= RoomId.GetHashCode();
      if (Idx != 0L) hash ^= Idx.GetHashCode();
      hash ^= characters_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ResponseCode != 0) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) ResponseCode);
      }
      if (GameServerId != 0L) {
        output.WriteRawTag(176, 6);
        output.WriteInt64(GameServerId);
      }
      if (RoomId != 0L) {
        output.WriteRawTag(184, 6);
        output.WriteInt64(RoomId);
      }
      if (Idx != 0L) {
        output.WriteRawTag(192, 6);
        output.WriteInt64(Idx);
      }
      characters_.WriteTo(output, _repeated_characters_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResponseCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseCode);
      }
      if (GameServerId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(GameServerId);
      }
      if (RoomId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(RoomId);
      }
      if (Idx != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Idx);
      }
      size += characters_.CalculateSize(_repeated_characters_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EnterRoom other) {
      if (other == null) {
        return;
      }
      if (other.ResponseCode != 0) {
        ResponseCode = other.ResponseCode;
      }
      if (other.GameServerId != 0L) {
        GameServerId = other.GameServerId;
      }
      if (other.RoomId != 0L) {
        RoomId = other.RoomId;
      }
      if (other.Idx != 0L) {
        Idx = other.Idx;
      }
      characters_.Add(other.characters_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 808: {
            responseCode_ = (global::Schema.Protobuf.Message.Enums.ResponseCode) input.ReadEnum();
            break;
          }
          case 816: {
            GameServerId = input.ReadInt64();
            break;
          }
          case 824: {
            RoomId = input.ReadInt64();
            break;
          }
          case 832: {
            Idx = input.ReadInt64();
            break;
          }
          case 842: {
            characters_.AddEntriesFrom(input, _repeated_characters_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class LeaveRoom : pb::IMessage<LeaveRoom> {
    private static readonly pb::MessageParser<LeaveRoom> _parser = new pb::MessageParser<LeaveRoom>(() => new LeaveRoom());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LeaveRoom> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaveRoom() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaveRoom(LeaveRoom other) : this() {
      responseCode_ = other.responseCode_;
      roomId_ = other.roomId_;
      idx_ = other.idx_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaveRoom Clone() {
      return new LeaveRoom(this);
    }

    /// <summary>Field number for the "ResponseCode" field.</summary>
    public const int ResponseCodeFieldNumber = 101;
    private global::Schema.Protobuf.Message.Enums.ResponseCode responseCode_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Enums.ResponseCode ResponseCode {
      get { return responseCode_; }
      set {
        responseCode_ = value;
      }
    }

    /// <summary>Field number for the "RoomId" field.</summary>
    public const int RoomIdFieldNumber = 102;
    private long roomId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long RoomId {
      get { return roomId_; }
      set {
        roomId_ = value;
      }
    }

    /// <summary>Field number for the "Idx" field.</summary>
    public const int IdxFieldNumber = 103;
    private long idx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Idx {
      get { return idx_; }
      set {
        idx_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LeaveRoom);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LeaveRoom other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResponseCode != other.ResponseCode) return false;
      if (RoomId != other.RoomId) return false;
      if (Idx != other.Idx) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResponseCode != 0) hash ^= ResponseCode.GetHashCode();
      if (RoomId != 0L) hash ^= RoomId.GetHashCode();
      if (Idx != 0L) hash ^= Idx.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ResponseCode != 0) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) ResponseCode);
      }
      if (RoomId != 0L) {
        output.WriteRawTag(176, 6);
        output.WriteInt64(RoomId);
      }
      if (Idx != 0L) {
        output.WriteRawTag(184, 6);
        output.WriteInt64(Idx);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResponseCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseCode);
      }
      if (RoomId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(RoomId);
      }
      if (Idx != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Idx);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LeaveRoom other) {
      if (other == null) {
        return;
      }
      if (other.ResponseCode != 0) {
        ResponseCode = other.ResponseCode;
      }
      if (other.RoomId != 0L) {
        RoomId = other.RoomId;
      }
      if (other.Idx != 0L) {
        Idx = other.Idx;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 808: {
            responseCode_ = (global::Schema.Protobuf.Message.Enums.ResponseCode) input.ReadEnum();
            break;
          }
          case 816: {
            RoomId = input.ReadInt64();
            break;
          }
          case 824: {
            Idx = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class EnterCharacter : pb::IMessage<EnterCharacter> {
    private static readonly pb::MessageParser<EnterCharacter> _parser = new pb::MessageParser<EnterCharacter>(() => new EnterCharacter());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EnterCharacter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterCharacter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterCharacter(EnterCharacter other) : this() {
      roomId_ = other.roomId_;
      Character = other.character_ != null ? other.Character.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterCharacter Clone() {
      return new EnterCharacter(this);
    }

    /// <summary>Field number for the "RoomId" field.</summary>
    public const int RoomIdFieldNumber = 101;
    private long roomId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long RoomId {
      get { return roomId_; }
      set {
        roomId_ = value;
      }
    }

    /// <summary>Field number for the "Character" field.</summary>
    public const int CharacterFieldNumber = 102;
    private global::Schema.Protobuf.Message.Common.Character character_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Common.Character Character {
      get { return character_; }
      set {
        character_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EnterCharacter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EnterCharacter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RoomId != other.RoomId) return false;
      if (!object.Equals(Character, other.Character)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RoomId != 0L) hash ^= RoomId.GetHashCode();
      if (character_ != null) hash ^= Character.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RoomId != 0L) {
        output.WriteRawTag(168, 6);
        output.WriteInt64(RoomId);
      }
      if (character_ != null) {
        output.WriteRawTag(178, 6);
        output.WriteMessage(Character);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RoomId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(RoomId);
      }
      if (character_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Character);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EnterCharacter other) {
      if (other == null) {
        return;
      }
      if (other.RoomId != 0L) {
        RoomId = other.RoomId;
      }
      if (other.character_ != null) {
        if (character_ == null) {
          character_ = new global::Schema.Protobuf.Message.Common.Character();
        }
        Character.MergeFrom(other.Character);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 808: {
            RoomId = input.ReadInt64();
            break;
          }
          case 818: {
            if (character_ == null) {
              character_ = new global::Schema.Protobuf.Message.Common.Character();
            }
            input.ReadMessage(character_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class LeaveCharacter : pb::IMessage<LeaveCharacter> {
    private static readonly pb::MessageParser<LeaveCharacter> _parser = new pb::MessageParser<LeaveCharacter>(() => new LeaveCharacter());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LeaveCharacter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaveCharacter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaveCharacter(LeaveCharacter other) : this() {
      roomId_ = other.roomId_;
      Character = other.character_ != null ? other.Character.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaveCharacter Clone() {
      return new LeaveCharacter(this);
    }

    /// <summary>Field number for the "RoomId" field.</summary>
    public const int RoomIdFieldNumber = 101;
    private long roomId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long RoomId {
      get { return roomId_; }
      set {
        roomId_ = value;
      }
    }

    /// <summary>Field number for the "Character" field.</summary>
    public const int CharacterFieldNumber = 102;
    private global::Schema.Protobuf.Message.Common.Character character_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Common.Character Character {
      get { return character_; }
      set {
        character_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LeaveCharacter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LeaveCharacter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RoomId != other.RoomId) return false;
      if (!object.Equals(Character, other.Character)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RoomId != 0L) hash ^= RoomId.GetHashCode();
      if (character_ != null) hash ^= Character.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RoomId != 0L) {
        output.WriteRawTag(168, 6);
        output.WriteInt64(RoomId);
      }
      if (character_ != null) {
        output.WriteRawTag(178, 6);
        output.WriteMessage(Character);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RoomId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(RoomId);
      }
      if (character_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Character);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LeaveCharacter other) {
      if (other == null) {
        return;
      }
      if (other.RoomId != 0L) {
        RoomId = other.RoomId;
      }
      if (other.character_ != null) {
        if (character_ == null) {
          character_ = new global::Schema.Protobuf.Message.Common.Character();
        }
        Character.MergeFrom(other.Character);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 808: {
            RoomId = input.ReadInt64();
            break;
          }
          case 818: {
            if (character_ == null) {
              character_ = new global::Schema.Protobuf.Message.Common.Character();
            }
            input.ReadMessage(character_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Damage : pb::IMessage<Damage> {
    private static readonly pb::MessageParser<Damage> _parser = new pb::MessageParser<Damage>(() => new Damage());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Damage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Damage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Damage(Damage other) : this() {
      idx_ = other.idx_;
      otherIdx_ = other.otherIdx_;
      power_ = other.power_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Damage Clone() {
      return new Damage(this);
    }

    /// <summary>Field number for the "Idx" field.</summary>
    public const int IdxFieldNumber = 1;
    private long idx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Idx {
      get { return idx_; }
      set {
        idx_ = value;
      }
    }

    /// <summary>Field number for the "OtherIdx" field.</summary>
    public const int OtherIdxFieldNumber = 2;
    private long otherIdx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long OtherIdx {
      get { return otherIdx_; }
      set {
        otherIdx_ = value;
      }
    }

    /// <summary>Field number for the "Power" field.</summary>
    public const int PowerFieldNumber = 3;
    private long power_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Power {
      get { return power_; }
      set {
        power_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Damage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Damage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Idx != other.Idx) return false;
      if (OtherIdx != other.OtherIdx) return false;
      if (Power != other.Power) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Idx != 0L) hash ^= Idx.GetHashCode();
      if (OtherIdx != 0L) hash ^= OtherIdx.GetHashCode();
      if (Power != 0L) hash ^= Power.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Idx != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Idx);
      }
      if (OtherIdx != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(OtherIdx);
      }
      if (Power != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Power);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Idx != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Idx);
      }
      if (OtherIdx != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(OtherIdx);
      }
      if (Power != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Power);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Damage other) {
      if (other == null) {
        return;
      }
      if (other.Idx != 0L) {
        Idx = other.Idx;
      }
      if (other.OtherIdx != 0L) {
        OtherIdx = other.OtherIdx;
      }
      if (other.Power != 0L) {
        Power = other.Power;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Idx = input.ReadInt64();
            break;
          }
          case 16: {
            OtherIdx = input.ReadInt64();
            break;
          }
          case 24: {
            Power = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Die : pb::IMessage<Die> {
    private static readonly pb::MessageParser<Die> _parser = new pb::MessageParser<Die>(() => new Die());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Die> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Die() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Die(Die other) : this() {
      idx_ = other.idx_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Die Clone() {
      return new Die(this);
    }

    /// <summary>Field number for the "Idx" field.</summary>
    public const int IdxFieldNumber = 101;
    private long idx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Idx {
      get { return idx_; }
      set {
        idx_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Die);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Die other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Idx != other.Idx) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Idx != 0L) hash ^= Idx.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Idx != 0L) {
        output.WriteRawTag(168, 6);
        output.WriteInt64(Idx);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Idx != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Idx);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Die other) {
      if (other == null) {
        return;
      }
      if (other.Idx != 0L) {
        Idx = other.Idx;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 808: {
            Idx = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class MyGameResult : pb::IMessage<MyGameResult> {
    private static readonly pb::MessageParser<MyGameResult> _parser = new pb::MessageParser<MyGameResult>(() => new MyGameResult());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MyGameResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MyGameResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MyGameResult(MyGameResult other) : this() {
      responseCode_ = other.responseCode_;
      Data = other.data_ != null ? other.Data.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MyGameResult Clone() {
      return new MyGameResult(this);
    }

    /// <summary>Field number for the "ResponseCode" field.</summary>
    public const int ResponseCodeFieldNumber = 101;
    private global::Schema.Protobuf.Message.Enums.ResponseCode responseCode_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Enums.ResponseCode ResponseCode {
      get { return responseCode_; }
      set {
        responseCode_ = value;
      }
    }

    /// <summary>Field number for the "Data" field.</summary>
    public const int DataFieldNumber = 102;
    private global::Schema.Protobuf.Message.Common.GameResult data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Common.GameResult Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MyGameResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MyGameResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResponseCode != other.ResponseCode) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResponseCode != 0) hash ^= ResponseCode.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ResponseCode != 0) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) ResponseCode);
      }
      if (data_ != null) {
        output.WriteRawTag(178, 6);
        output.WriteMessage(Data);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResponseCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseCode);
      }
      if (data_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MyGameResult other) {
      if (other == null) {
        return;
      }
      if (other.ResponseCode != 0) {
        ResponseCode = other.ResponseCode;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          data_ = new global::Schema.Protobuf.Message.Common.GameResult();
        }
        Data.MergeFrom(other.Data);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 808: {
            responseCode_ = (global::Schema.Protobuf.Message.Enums.ResponseCode) input.ReadEnum();
            break;
          }
          case 818: {
            if (data_ == null) {
              data_ = new global::Schema.Protobuf.Message.Common.GameResult();
            }
            input.ReadMessage(data_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class FinishGame : pb::IMessage<FinishGame> {
    private static readonly pb::MessageParser<FinishGame> _parser = new pb::MessageParser<FinishGame>(() => new FinishGame());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FinishGame> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FinishGame() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FinishGame(FinishGame other) : this() {
      responseCode_ = other.responseCode_;
      datas_ = other.datas_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FinishGame Clone() {
      return new FinishGame(this);
    }

    /// <summary>Field number for the "ResponseCode" field.</summary>
    public const int ResponseCodeFieldNumber = 101;
    private global::Schema.Protobuf.Message.Enums.ResponseCode responseCode_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Enums.ResponseCode ResponseCode {
      get { return responseCode_; }
      set {
        responseCode_ = value;
      }
    }

    /// <summary>Field number for the "Datas" field.</summary>
    public const int DatasFieldNumber = 102;
    private static readonly pb::FieldCodec<global::Schema.Protobuf.Message.Common.GameResult> _repeated_datas_codec
        = pb::FieldCodec.ForMessage(818, global::Schema.Protobuf.Message.Common.GameResult.Parser);
    private readonly pbc::RepeatedField<global::Schema.Protobuf.Message.Common.GameResult> datas_ = new pbc::RepeatedField<global::Schema.Protobuf.Message.Common.GameResult>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Schema.Protobuf.Message.Common.GameResult> Datas {
      get { return datas_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FinishGame);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FinishGame other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResponseCode != other.ResponseCode) return false;
      if(!datas_.Equals(other.datas_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResponseCode != 0) hash ^= ResponseCode.GetHashCode();
      hash ^= datas_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ResponseCode != 0) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) ResponseCode);
      }
      datas_.WriteTo(output, _repeated_datas_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResponseCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseCode);
      }
      size += datas_.CalculateSize(_repeated_datas_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FinishGame other) {
      if (other == null) {
        return;
      }
      if (other.ResponseCode != 0) {
        ResponseCode = other.ResponseCode;
      }
      datas_.Add(other.datas_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 808: {
            responseCode_ = (global::Schema.Protobuf.Message.Enums.ResponseCode) input.ReadEnum();
            break;
          }
          case 818: {
            datas_.AddEntriesFrom(input, _repeated_datas_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Chat : pb::IMessage<Chat> {
    private static readonly pb::MessageParser<Chat> _parser = new pb::MessageParser<Chat>(() => new Chat());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Chat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Chat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Chat(Chat other) : this() {
      idx_ = other.idx_;
      id_ = other.id_;
      msg_ = other.msg_;
      responseCode_ = other.responseCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Chat Clone() {
      return new Chat(this);
    }

    /// <summary>Field number for the "Idx" field.</summary>
    public const int IdxFieldNumber = 1;
    private long idx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Idx {
      get { return idx_; }
      set {
        idx_ = value;
      }
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 2;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 3;
    private string msg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Msg {
      get { return msg_; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ResponseCode" field.</summary>
    public const int ResponseCodeFieldNumber = 101;
    private global::Schema.Protobuf.Message.Enums.ResponseCode responseCode_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Enums.ResponseCode ResponseCode {
      get { return responseCode_; }
      set {
        responseCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Chat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Chat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Idx != other.Idx) return false;
      if (Id != other.Id) return false;
      if (Msg != other.Msg) return false;
      if (ResponseCode != other.ResponseCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Idx != 0L) hash ^= Idx.GetHashCode();
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Msg.Length != 0) hash ^= Msg.GetHashCode();
      if (ResponseCode != 0) hash ^= ResponseCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Idx != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Idx);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Id);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Msg);
      }
      if (ResponseCode != 0) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) ResponseCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Idx != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Idx);
      }
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Msg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (ResponseCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Chat other) {
      if (other == null) {
        return;
      }
      if (other.Idx != 0L) {
        Idx = other.Idx;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Msg.Length != 0) {
        Msg = other.Msg;
      }
      if (other.ResponseCode != 0) {
        ResponseCode = other.ResponseCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Idx = input.ReadInt64();
            break;
          }
          case 18: {
            Id = input.ReadString();
            break;
          }
          case 26: {
            Msg = input.ReadString();
            break;
          }
          case 808: {
            responseCode_ = (global::Schema.Protobuf.Message.Enums.ResponseCode) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SyncTime : pb::IMessage<SyncTime> {
    private static readonly pb::MessageParser<SyncTime> _parser = new pb::MessageParser<SyncTime>(() => new SyncTime());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SyncTime> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[12]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SyncTime() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SyncTime(SyncTime other) : this() {
      sendLocalTime_ = other.sendLocalTime_;
      recvLocalTime_ = other.recvLocalTime_;
      remoteTime_ = other.remoteTime_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SyncTime Clone() {
      return new SyncTime(this);
    }

    /// <summary>Field number for the "SendLocalTime" field.</summary>
    public const int SendLocalTimeFieldNumber = 1;
    private long sendLocalTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long SendLocalTime {
      get { return sendLocalTime_; }
      set {
        sendLocalTime_ = value;
      }
    }

    /// <summary>Field number for the "RecvLocalTime" field.</summary>
    public const int RecvLocalTimeFieldNumber = 2;
    private long recvLocalTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long RecvLocalTime {
      get { return recvLocalTime_; }
      set {
        recvLocalTime_ = value;
      }
    }

    /// <summary>Field number for the "RemoteTime" field.</summary>
    public const int RemoteTimeFieldNumber = 101;
    private long remoteTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long RemoteTime {
      get { return remoteTime_; }
      set {
        remoteTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SyncTime);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SyncTime other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SendLocalTime != other.SendLocalTime) return false;
      if (RecvLocalTime != other.RecvLocalTime) return false;
      if (RemoteTime != other.RemoteTime) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SendLocalTime != 0L) hash ^= SendLocalTime.GetHashCode();
      if (RecvLocalTime != 0L) hash ^= RecvLocalTime.GetHashCode();
      if (RemoteTime != 0L) hash ^= RemoteTime.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SendLocalTime != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(SendLocalTime);
      }
      if (RecvLocalTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(RecvLocalTime);
      }
      if (RemoteTime != 0L) {
        output.WriteRawTag(168, 6);
        output.WriteInt64(RemoteTime);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SendLocalTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SendLocalTime);
      }
      if (RecvLocalTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RecvLocalTime);
      }
      if (RemoteTime != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(RemoteTime);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SyncTime other) {
      if (other == null) {
        return;
      }
      if (other.SendLocalTime != 0L) {
        SendLocalTime = other.SendLocalTime;
      }
      if (other.RecvLocalTime != 0L) {
        RecvLocalTime = other.RecvLocalTime;
      }
      if (other.RemoteTime != 0L) {
        RemoteTime = other.RemoteTime;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            SendLocalTime = input.ReadInt64();
            break;
          }
          case 16: {
            RecvLocalTime = input.ReadInt64();
            break;
          }
          case 808: {
            RemoteTime = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Move : pb::IMessage<Move> {
    private static readonly pb::MessageParser<Move> _parser = new pb::MessageParser<Move>(() => new Move());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Move> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[13]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Move() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Move(Move other) : this() {
      idx_ = other.idx_;
      Position = other.position_ != null ? other.Position.Clone() : null;
      Direction = other.direction_ != null ? other.Direction.Clone() : null;
      speed_ = other.speed_;
      ticks_ = other.ticks_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Move Clone() {
      return new Move(this);
    }

    /// <summary>Field number for the "Idx" field.</summary>
    public const int IdxFieldNumber = 1;
    private long idx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Idx {
      get { return idx_; }
      set {
        idx_ = value;
      }
    }

    /// <summary>Field number for the "Position" field.</summary>
    public const int PositionFieldNumber = 2;
    private global::Schema.Protobuf.Message.Common.Vector3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Common.Vector3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "Direction" field.</summary>
    public const int DirectionFieldNumber = 3;
    private global::Schema.Protobuf.Message.Common.Vector3 direction_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Common.Vector3 Direction {
      get { return direction_; }
      set {
        direction_ = value;
      }
    }

    /// <summary>Field number for the "Speed" field.</summary>
    public const int SpeedFieldNumber = 4;
    private float speed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Speed {
      get { return speed_; }
      set {
        speed_ = value;
      }
    }

    /// <summary>Field number for the "Ticks" field.</summary>
    public const int TicksFieldNumber = 5;
    private long ticks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Ticks {
      get { return ticks_; }
      set {
        ticks_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Move);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Move other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Idx != other.Idx) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (!object.Equals(Direction, other.Direction)) return false;
      if (Speed != other.Speed) return false;
      if (Ticks != other.Ticks) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Idx != 0L) hash ^= Idx.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (direction_ != null) hash ^= Direction.GetHashCode();
      if (Speed != 0F) hash ^= Speed.GetHashCode();
      if (Ticks != 0L) hash ^= Ticks.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Idx != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Idx);
      }
      if (position_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Position);
      }
      if (direction_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Direction);
      }
      if (Speed != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Speed);
      }
      if (Ticks != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Ticks);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Idx != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Idx);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (direction_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Direction);
      }
      if (Speed != 0F) {
        size += 1 + 4;
      }
      if (Ticks != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Ticks);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Move other) {
      if (other == null) {
        return;
      }
      if (other.Idx != 0L) {
        Idx = other.Idx;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          position_ = new global::Schema.Protobuf.Message.Common.Vector3();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.direction_ != null) {
        if (direction_ == null) {
          direction_ = new global::Schema.Protobuf.Message.Common.Vector3();
        }
        Direction.MergeFrom(other.Direction);
      }
      if (other.Speed != 0F) {
        Speed = other.Speed;
      }
      if (other.Ticks != 0L) {
        Ticks = other.Ticks;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Idx = input.ReadInt64();
            break;
          }
          case 18: {
            if (position_ == null) {
              position_ = new global::Schema.Protobuf.Message.Common.Vector3();
            }
            input.ReadMessage(position_);
            break;
          }
          case 26: {
            if (direction_ == null) {
              direction_ = new global::Schema.Protobuf.Message.Common.Vector3();
            }
            input.ReadMessage(direction_);
            break;
          }
          case 37: {
            Speed = input.ReadFloat();
            break;
          }
          case 40: {
            Ticks = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RTT : pb::IMessage<RTT> {
    private static readonly pb::MessageParser<RTT> _parser = new pb::MessageParser<RTT>(() => new RTT());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RTT> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[14]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RTT() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RTT(RTT other) : this() {
      idx_ = other.idx_;
      seq_ = other.seq_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RTT Clone() {
      return new RTT(this);
    }

    /// <summary>Field number for the "Idx" field.</summary>
    public const int IdxFieldNumber = 1;
    private long idx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Idx {
      get { return idx_; }
      set {
        idx_ = value;
      }
    }

    /// <summary>Field number for the "Seq" field.</summary>
    public const int SeqFieldNumber = 2;
    private long seq_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Seq {
      get { return seq_; }
      set {
        seq_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RTT);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RTT other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Idx != other.Idx) return false;
      if (Seq != other.Seq) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Idx != 0L) hash ^= Idx.GetHashCode();
      if (Seq != 0L) hash ^= Seq.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Idx != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Idx);
      }
      if (Seq != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Seq);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Idx != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Idx);
      }
      if (Seq != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Seq);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RTT other) {
      if (other == null) {
        return;
      }
      if (other.Idx != 0L) {
        Idx = other.Idx;
      }
      if (other.Seq != 0L) {
        Seq = other.Seq;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Idx = input.ReadInt64();
            break;
          }
          case 16: {
            Seq = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class World : pb::IMessage<World> {
    private static readonly pb::MessageParser<World> _parser = new pb::MessageParser<World>(() => new World());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<World> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[15]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public World() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public World(World other) : this() {
      characters_ = other.characters_.Clone();
      Map = other.map_ != null ? other.Map.Clone() : null;
      seq_ = other.seq_;
      deltaTicks_ = other.deltaTicks_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public World Clone() {
      return new World(this);
    }

    /// <summary>Field number for the "Characters" field.</summary>
    public const int CharactersFieldNumber = 101;
    private static readonly pb::FieldCodec<global::Schema.Protobuf.Message.Common.Character> _repeated_characters_codec
        = pb::FieldCodec.ForMessage(810, global::Schema.Protobuf.Message.Common.Character.Parser);
    private readonly pbc::RepeatedField<global::Schema.Protobuf.Message.Common.Character> characters_ = new pbc::RepeatedField<global::Schema.Protobuf.Message.Common.Character>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Schema.Protobuf.Message.Common.Character> Characters {
      get { return characters_; }
    }

    /// <summary>Field number for the "Map" field.</summary>
    public const int MapFieldNumber = 102;
    private global::Schema.Protobuf.Message.Common.PlaneMap map_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Common.PlaneMap Map {
      get { return map_; }
      set {
        map_ = value;
      }
    }

    /// <summary>Field number for the "Seq" field.</summary>
    public const int SeqFieldNumber = 103;
    private long seq_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Seq {
      get { return seq_; }
      set {
        seq_ = value;
      }
    }

    /// <summary>Field number for the "DeltaTicks" field.</summary>
    public const int DeltaTicksFieldNumber = 104;
    private long deltaTicks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long DeltaTicks {
      get { return deltaTicks_; }
      set {
        deltaTicks_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as World);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(World other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!characters_.Equals(other.characters_)) return false;
      if (!object.Equals(Map, other.Map)) return false;
      if (Seq != other.Seq) return false;
      if (DeltaTicks != other.DeltaTicks) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= characters_.GetHashCode();
      if (map_ != null) hash ^= Map.GetHashCode();
      if (Seq != 0L) hash ^= Seq.GetHashCode();
      if (DeltaTicks != 0L) hash ^= DeltaTicks.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      characters_.WriteTo(output, _repeated_characters_codec);
      if (map_ != null) {
        output.WriteRawTag(178, 6);
        output.WriteMessage(Map);
      }
      if (Seq != 0L) {
        output.WriteRawTag(184, 6);
        output.WriteInt64(Seq);
      }
      if (DeltaTicks != 0L) {
        output.WriteRawTag(192, 6);
        output.WriteInt64(DeltaTicks);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += characters_.CalculateSize(_repeated_characters_codec);
      if (map_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Map);
      }
      if (Seq != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Seq);
      }
      if (DeltaTicks != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(DeltaTicks);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(World other) {
      if (other == null) {
        return;
      }
      characters_.Add(other.characters_);
      if (other.map_ != null) {
        if (map_ == null) {
          map_ = new global::Schema.Protobuf.Message.Common.PlaneMap();
        }
        Map.MergeFrom(other.Map);
      }
      if (other.Seq != 0L) {
        Seq = other.Seq;
      }
      if (other.DeltaTicks != 0L) {
        DeltaTicks = other.DeltaTicks;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 810: {
            characters_.AddEntriesFrom(input, _repeated_characters_codec);
            break;
          }
          case 818: {
            if (map_ == null) {
              map_ = new global::Schema.Protobuf.Message.Common.PlaneMap();
            }
            input.ReadMessage(map_);
            break;
          }
          case 824: {
            Seq = input.ReadInt64();
            break;
          }
          case 832: {
            DeltaTicks = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
