// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enums.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Schema.Protobuf.Message.Enums {

  /// <summary>Holder for reflection information generated from Enums.proto</summary>
  public static partial class EnumsReflection {

    #region Descriptor
    /// <summary>File descriptor for Enums.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtFbnVtcy5wcm90bxIdU2NoZW1hLlByb3RvYnVmLk1lc3NhZ2UuRW51bXMq",
            "VgoMUmVzcG9uc2VDb2RlEhUKEVJlc3BvbnNlQ29kZV9OT05FEAASFQoRUmVz",
            "cG9uc2VDb2RlX0ZBSUwQARIYChRSZXNwb25zZUNvZGVfU1VDQ0VTUxACKnkK",
            "DkNsaWVudFBsYXRmb3JtEhcKE0NMSUVOVFBMQVRGT1JNX05PTkUQABIZChVD",
            "TElFTlRQTEFURk9STV9FRElUT1IQARIZChVDTElFTlRQTEFURk9STV9HT09H",
            "TEUQAhIYChRDTElFTlRQTEFURk9STV9BUFBMRRADYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Schema.Protobuf.Message.Enums.ResponseCode), typeof(global::Schema.Protobuf.Message.Enums.ClientPlatform), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ResponseCode {
    [pbr::OriginalName("ResponseCode_NONE")] None = 0,
    [pbr::OriginalName("ResponseCode_FAIL")] Fail = 1,
    [pbr::OriginalName("ResponseCode_SUCCESS")] Success = 2,
  }

  public enum ClientPlatform {
    [pbr::OriginalName("CLIENTPLATFORM_NONE")] None = 0,
    [pbr::OriginalName("CLIENTPLATFORM_EDITOR")] Editor = 1,
    [pbr::OriginalName("CLIENTPLATFORM_GOOGLE")] Google = 2,
    [pbr::OriginalName("CLIENTPLATFORM_APPLE")] Apple = 3,
  }

  #endregion

}

#endregion Designer generated code
