// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Game.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Schema.Protobuf.Message.Game {

  /// <summary>Holder for reflection information generated from Game.proto</summary>
  public static partial class GameReflection {

    #region Descriptor
    /// <summary>File descriptor for Game.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpHYW1lLnByb3RvEhxTY2hlbWEuUHJvdG9idWYuTWVzc2FnZS5HYW1lGgtF",
            "bnVtcy5wcm90bxoMQ29tbW9uLnByb3RvIl8KDUJlZ2luTWF0Y2hpbmcSCwoD",
            "TU1SGAEgASgFEkEKDFJlc3BvbnNlQ29kZRhlIAEoDjIrLlNjaGVtYS5Qcm90",
            "b2J1Zi5NZXNzYWdlLkVudW1zLlJlc3BvbnNlQ29kZSJTCg5DYW5jZWxNYXRj",
            "aGluZxJBCgxSZXNwb25zZUNvZGUYZSABKA4yKy5TY2hlbWEuUHJvdG9idWYu",
            "TWVzc2FnZS5FbnVtcy5SZXNwb25zZUNvZGUilAEKC0VuZE1hdGNoaW5nEkEK",
            "DFJlc3BvbnNlQ29kZRhlIAEoDjIrLlNjaGVtYS5Qcm90b2J1Zi5NZXNzYWdl",
            "LkVudW1zLlJlc3BvbnNlQ29kZRJCCgxNYXRjaGluZ0luZm8YZiABKAsyLC5T",
            "Y2hlbWEuUHJvdG9idWYuTWVzc2FnZS5Db21tb24uTWF0Y2hpbmdJbmZvIoEB",
            "CglFbnRlclJvb20SQQoMUmVzcG9uc2VDb2RlGGUgASgOMisuU2NoZW1hLlBy",
            "b3RvYnVmLk1lc3NhZ2UuRW51bXMuUmVzcG9uc2VDb2RlEhQKDEdhbWVTZXJ2",
            "ZXJJZBhmIAEoAxIOCgZSb29tSWQYZyABKAMSCwoDSWR4GGggASgDIosBCgxN",
            "eUdhbWVSZXN1bHQSQQoMUmVzcG9uc2VDb2RlGGUgASgOMisuU2NoZW1hLlBy",
            "b3RvYnVmLk1lc3NhZ2UuRW51bXMuUmVzcG9uc2VDb2RlEjgKBERhdGEYZiAB",
            "KAsyKi5TY2hlbWEuUHJvdG9idWYuTWVzc2FnZS5Db21tb24uR2FtZVJlc3Vs",
            "dCKKAQoKRmluaXNoR2FtZRJBCgxSZXNwb25zZUNvZGUYZSABKA4yKy5TY2hl",
            "bWEuUHJvdG9idWYuTWVzc2FnZS5FbnVtcy5SZXNwb25zZUNvZGUSOQoFRGF0",
            "YXMYZiADKAsyKi5TY2hlbWEuUHJvdG9idWYuTWVzc2FnZS5Db21tb24uR2Ft",
            "ZVJlc3VsdCJvCgRDaGF0EgsKA0lkeBgBIAEoAxIKCgJJZBgCIAEoCRILCgNt",
            "c2cYAyABKAkSQQoMUmVzcG9uc2VDb2RlGGUgASgOMisuU2NoZW1hLlByb3Rv",
            "YnVmLk1lc3NhZ2UuRW51bXMuUmVzcG9uc2VDb2RlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Schema.Protobuf.Message.Enums.EnumsReflection.Descriptor, global::Schema.Protobuf.Message.Common.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.BeginMatching), global::Schema.Protobuf.Message.Game.BeginMatching.Parser, new[]{ "MMR", "ResponseCode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.CancelMatching), global::Schema.Protobuf.Message.Game.CancelMatching.Parser, new[]{ "ResponseCode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.EndMatching), global::Schema.Protobuf.Message.Game.EndMatching.Parser, new[]{ "ResponseCode", "MatchingInfo" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.EnterRoom), global::Schema.Protobuf.Message.Game.EnterRoom.Parser, new[]{ "ResponseCode", "GameServerId", "RoomId", "Idx" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.MyGameResult), global::Schema.Protobuf.Message.Game.MyGameResult.Parser, new[]{ "ResponseCode", "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.FinishGame), global::Schema.Protobuf.Message.Game.FinishGame.Parser, new[]{ "ResponseCode", "Datas" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Schema.Protobuf.Message.Game.Chat), global::Schema.Protobuf.Message.Game.Chat.Parser, new[]{ "Idx", "Id", "Msg", "ResponseCode" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class BeginMatching : pb::IMessage<BeginMatching> {
    private static readonly pb::MessageParser<BeginMatching> _parser = new pb::MessageParser<BeginMatching>(() => new BeginMatching());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BeginMatching> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BeginMatching() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BeginMatching(BeginMatching other) : this() {
      mMR_ = other.mMR_;
      responseCode_ = other.responseCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BeginMatching Clone() {
      return new BeginMatching(this);
    }

    /// <summary>Field number for the "MMR" field.</summary>
    public const int MMRFieldNumber = 1;
    private int mMR_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MMR {
      get { return mMR_; }
      set {
        mMR_ = value;
      }
    }

    /// <summary>Field number for the "ResponseCode" field.</summary>
    public const int ResponseCodeFieldNumber = 101;
    private global::Schema.Protobuf.Message.Enums.ResponseCode responseCode_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Enums.ResponseCode ResponseCode {
      get { return responseCode_; }
      set {
        responseCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BeginMatching);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BeginMatching other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MMR != other.MMR) return false;
      if (ResponseCode != other.ResponseCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MMR != 0) hash ^= MMR.GetHashCode();
      if (ResponseCode != 0) hash ^= ResponseCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MMR != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MMR);
      }
      if (ResponseCode != 0) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) ResponseCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MMR != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MMR);
      }
      if (ResponseCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BeginMatching other) {
      if (other == null) {
        return;
      }
      if (other.MMR != 0) {
        MMR = other.MMR;
      }
      if (other.ResponseCode != 0) {
        ResponseCode = other.ResponseCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            MMR = input.ReadInt32();
            break;
          }
          case 808: {
            responseCode_ = (global::Schema.Protobuf.Message.Enums.ResponseCode) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CancelMatching : pb::IMessage<CancelMatching> {
    private static readonly pb::MessageParser<CancelMatching> _parser = new pb::MessageParser<CancelMatching>(() => new CancelMatching());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CancelMatching> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CancelMatching() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CancelMatching(CancelMatching other) : this() {
      responseCode_ = other.responseCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CancelMatching Clone() {
      return new CancelMatching(this);
    }

    /// <summary>Field number for the "ResponseCode" field.</summary>
    public const int ResponseCodeFieldNumber = 101;
    private global::Schema.Protobuf.Message.Enums.ResponseCode responseCode_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Enums.ResponseCode ResponseCode {
      get { return responseCode_; }
      set {
        responseCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CancelMatching);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CancelMatching other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResponseCode != other.ResponseCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResponseCode != 0) hash ^= ResponseCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ResponseCode != 0) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) ResponseCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResponseCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CancelMatching other) {
      if (other == null) {
        return;
      }
      if (other.ResponseCode != 0) {
        ResponseCode = other.ResponseCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 808: {
            responseCode_ = (global::Schema.Protobuf.Message.Enums.ResponseCode) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class EndMatching : pb::IMessage<EndMatching> {
    private static readonly pb::MessageParser<EndMatching> _parser = new pb::MessageParser<EndMatching>(() => new EndMatching());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EndMatching> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EndMatching() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EndMatching(EndMatching other) : this() {
      responseCode_ = other.responseCode_;
      MatchingInfo = other.matchingInfo_ != null ? other.MatchingInfo.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EndMatching Clone() {
      return new EndMatching(this);
    }

    /// <summary>Field number for the "ResponseCode" field.</summary>
    public const int ResponseCodeFieldNumber = 101;
    private global::Schema.Protobuf.Message.Enums.ResponseCode responseCode_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Enums.ResponseCode ResponseCode {
      get { return responseCode_; }
      set {
        responseCode_ = value;
      }
    }

    /// <summary>Field number for the "MatchingInfo" field.</summary>
    public const int MatchingInfoFieldNumber = 102;
    private global::Schema.Protobuf.Message.Common.MatchingInfo matchingInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Common.MatchingInfo MatchingInfo {
      get { return matchingInfo_; }
      set {
        matchingInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EndMatching);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EndMatching other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResponseCode != other.ResponseCode) return false;
      if (!object.Equals(MatchingInfo, other.MatchingInfo)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResponseCode != 0) hash ^= ResponseCode.GetHashCode();
      if (matchingInfo_ != null) hash ^= MatchingInfo.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ResponseCode != 0) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) ResponseCode);
      }
      if (matchingInfo_ != null) {
        output.WriteRawTag(178, 6);
        output.WriteMessage(MatchingInfo);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResponseCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseCode);
      }
      if (matchingInfo_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(MatchingInfo);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EndMatching other) {
      if (other == null) {
        return;
      }
      if (other.ResponseCode != 0) {
        ResponseCode = other.ResponseCode;
      }
      if (other.matchingInfo_ != null) {
        if (matchingInfo_ == null) {
          matchingInfo_ = new global::Schema.Protobuf.Message.Common.MatchingInfo();
        }
        MatchingInfo.MergeFrom(other.MatchingInfo);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 808: {
            responseCode_ = (global::Schema.Protobuf.Message.Enums.ResponseCode) input.ReadEnum();
            break;
          }
          case 818: {
            if (matchingInfo_ == null) {
              matchingInfo_ = new global::Schema.Protobuf.Message.Common.MatchingInfo();
            }
            input.ReadMessage(matchingInfo_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class EnterRoom : pb::IMessage<EnterRoom> {
    private static readonly pb::MessageParser<EnterRoom> _parser = new pb::MessageParser<EnterRoom>(() => new EnterRoom());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EnterRoom> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterRoom() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterRoom(EnterRoom other) : this() {
      responseCode_ = other.responseCode_;
      gameServerId_ = other.gameServerId_;
      roomId_ = other.roomId_;
      idx_ = other.idx_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterRoom Clone() {
      return new EnterRoom(this);
    }

    /// <summary>Field number for the "ResponseCode" field.</summary>
    public const int ResponseCodeFieldNumber = 101;
    private global::Schema.Protobuf.Message.Enums.ResponseCode responseCode_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Enums.ResponseCode ResponseCode {
      get { return responseCode_; }
      set {
        responseCode_ = value;
      }
    }

    /// <summary>Field number for the "GameServerId" field.</summary>
    public const int GameServerIdFieldNumber = 102;
    private long gameServerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long GameServerId {
      get { return gameServerId_; }
      set {
        gameServerId_ = value;
      }
    }

    /// <summary>Field number for the "RoomId" field.</summary>
    public const int RoomIdFieldNumber = 103;
    private long roomId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long RoomId {
      get { return roomId_; }
      set {
        roomId_ = value;
      }
    }

    /// <summary>Field number for the "Idx" field.</summary>
    public const int IdxFieldNumber = 104;
    private long idx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Idx {
      get { return idx_; }
      set {
        idx_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EnterRoom);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EnterRoom other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResponseCode != other.ResponseCode) return false;
      if (GameServerId != other.GameServerId) return false;
      if (RoomId != other.RoomId) return false;
      if (Idx != other.Idx) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResponseCode != 0) hash ^= ResponseCode.GetHashCode();
      if (GameServerId != 0L) hash ^= GameServerId.GetHashCode();
      if (RoomId != 0L) hash ^= RoomId.GetHashCode();
      if (Idx != 0L) hash ^= Idx.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ResponseCode != 0) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) ResponseCode);
      }
      if (GameServerId != 0L) {
        output.WriteRawTag(176, 6);
        output.WriteInt64(GameServerId);
      }
      if (RoomId != 0L) {
        output.WriteRawTag(184, 6);
        output.WriteInt64(RoomId);
      }
      if (Idx != 0L) {
        output.WriteRawTag(192, 6);
        output.WriteInt64(Idx);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResponseCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseCode);
      }
      if (GameServerId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(GameServerId);
      }
      if (RoomId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(RoomId);
      }
      if (Idx != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Idx);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EnterRoom other) {
      if (other == null) {
        return;
      }
      if (other.ResponseCode != 0) {
        ResponseCode = other.ResponseCode;
      }
      if (other.GameServerId != 0L) {
        GameServerId = other.GameServerId;
      }
      if (other.RoomId != 0L) {
        RoomId = other.RoomId;
      }
      if (other.Idx != 0L) {
        Idx = other.Idx;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 808: {
            responseCode_ = (global::Schema.Protobuf.Message.Enums.ResponseCode) input.ReadEnum();
            break;
          }
          case 816: {
            GameServerId = input.ReadInt64();
            break;
          }
          case 824: {
            RoomId = input.ReadInt64();
            break;
          }
          case 832: {
            Idx = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class MyGameResult : pb::IMessage<MyGameResult> {
    private static readonly pb::MessageParser<MyGameResult> _parser = new pb::MessageParser<MyGameResult>(() => new MyGameResult());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MyGameResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MyGameResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MyGameResult(MyGameResult other) : this() {
      responseCode_ = other.responseCode_;
      Data = other.data_ != null ? other.Data.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MyGameResult Clone() {
      return new MyGameResult(this);
    }

    /// <summary>Field number for the "ResponseCode" field.</summary>
    public const int ResponseCodeFieldNumber = 101;
    private global::Schema.Protobuf.Message.Enums.ResponseCode responseCode_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Enums.ResponseCode ResponseCode {
      get { return responseCode_; }
      set {
        responseCode_ = value;
      }
    }

    /// <summary>Field number for the "Data" field.</summary>
    public const int DataFieldNumber = 102;
    private global::Schema.Protobuf.Message.Common.GameResult data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Common.GameResult Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MyGameResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MyGameResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResponseCode != other.ResponseCode) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResponseCode != 0) hash ^= ResponseCode.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ResponseCode != 0) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) ResponseCode);
      }
      if (data_ != null) {
        output.WriteRawTag(178, 6);
        output.WriteMessage(Data);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResponseCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseCode);
      }
      if (data_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MyGameResult other) {
      if (other == null) {
        return;
      }
      if (other.ResponseCode != 0) {
        ResponseCode = other.ResponseCode;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          data_ = new global::Schema.Protobuf.Message.Common.GameResult();
        }
        Data.MergeFrom(other.Data);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 808: {
            responseCode_ = (global::Schema.Protobuf.Message.Enums.ResponseCode) input.ReadEnum();
            break;
          }
          case 818: {
            if (data_ == null) {
              data_ = new global::Schema.Protobuf.Message.Common.GameResult();
            }
            input.ReadMessage(data_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class FinishGame : pb::IMessage<FinishGame> {
    private static readonly pb::MessageParser<FinishGame> _parser = new pb::MessageParser<FinishGame>(() => new FinishGame());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FinishGame> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FinishGame() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FinishGame(FinishGame other) : this() {
      responseCode_ = other.responseCode_;
      datas_ = other.datas_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FinishGame Clone() {
      return new FinishGame(this);
    }

    /// <summary>Field number for the "ResponseCode" field.</summary>
    public const int ResponseCodeFieldNumber = 101;
    private global::Schema.Protobuf.Message.Enums.ResponseCode responseCode_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Enums.ResponseCode ResponseCode {
      get { return responseCode_; }
      set {
        responseCode_ = value;
      }
    }

    /// <summary>Field number for the "Datas" field.</summary>
    public const int DatasFieldNumber = 102;
    private static readonly pb::FieldCodec<global::Schema.Protobuf.Message.Common.GameResult> _repeated_datas_codec
        = pb::FieldCodec.ForMessage(818, global::Schema.Protobuf.Message.Common.GameResult.Parser);
    private readonly pbc::RepeatedField<global::Schema.Protobuf.Message.Common.GameResult> datas_ = new pbc::RepeatedField<global::Schema.Protobuf.Message.Common.GameResult>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Schema.Protobuf.Message.Common.GameResult> Datas {
      get { return datas_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FinishGame);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FinishGame other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResponseCode != other.ResponseCode) return false;
      if(!datas_.Equals(other.datas_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResponseCode != 0) hash ^= ResponseCode.GetHashCode();
      hash ^= datas_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ResponseCode != 0) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) ResponseCode);
      }
      datas_.WriteTo(output, _repeated_datas_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResponseCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseCode);
      }
      size += datas_.CalculateSize(_repeated_datas_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FinishGame other) {
      if (other == null) {
        return;
      }
      if (other.ResponseCode != 0) {
        ResponseCode = other.ResponseCode;
      }
      datas_.Add(other.datas_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 808: {
            responseCode_ = (global::Schema.Protobuf.Message.Enums.ResponseCode) input.ReadEnum();
            break;
          }
          case 818: {
            datas_.AddEntriesFrom(input, _repeated_datas_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Chat : pb::IMessage<Chat> {
    private static readonly pb::MessageParser<Chat> _parser = new pb::MessageParser<Chat>(() => new Chat());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Chat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Schema.Protobuf.Message.Game.GameReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Chat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Chat(Chat other) : this() {
      idx_ = other.idx_;
      id_ = other.id_;
      msg_ = other.msg_;
      responseCode_ = other.responseCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Chat Clone() {
      return new Chat(this);
    }

    /// <summary>Field number for the "Idx" field.</summary>
    public const int IdxFieldNumber = 1;
    private long idx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Idx {
      get { return idx_; }
      set {
        idx_ = value;
      }
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 2;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 3;
    private string msg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Msg {
      get { return msg_; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ResponseCode" field.</summary>
    public const int ResponseCodeFieldNumber = 101;
    private global::Schema.Protobuf.Message.Enums.ResponseCode responseCode_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Schema.Protobuf.Message.Enums.ResponseCode ResponseCode {
      get { return responseCode_; }
      set {
        responseCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Chat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Chat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Idx != other.Idx) return false;
      if (Id != other.Id) return false;
      if (Msg != other.Msg) return false;
      if (ResponseCode != other.ResponseCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Idx != 0L) hash ^= Idx.GetHashCode();
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Msg.Length != 0) hash ^= Msg.GetHashCode();
      if (ResponseCode != 0) hash ^= ResponseCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Idx != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Idx);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Id);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Msg);
      }
      if (ResponseCode != 0) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) ResponseCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Idx != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Idx);
      }
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Msg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (ResponseCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Chat other) {
      if (other == null) {
        return;
      }
      if (other.Idx != 0L) {
        Idx = other.Idx;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Msg.Length != 0) {
        Msg = other.Msg;
      }
      if (other.ResponseCode != 0) {
        ResponseCode = other.ResponseCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Idx = input.ReadInt64();
            break;
          }
          case 18: {
            Id = input.ReadString();
            break;
          }
          case 26: {
            Msg = input.ReadString();
            break;
          }
          case 808: {
            responseCode_ = (global::Schema.Protobuf.Message.Enums.ResponseCode) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
